#!/bin/sh

set -eu

tags="$(
  gh api 'repos/actions/runner-images/releases?per_page=100' --jq '
  [
    .[]
    | select(.prerelease == false and .draft == false)
    | select(.tag_name | contains("macos"))
    | select(.tag_name | contains("arm64"))
    | if (.tag_name | test("^macos-[0-9]+-arm64/.+$"))
        then .
        else error("invalid tag format: \(.tag_name)")
      end
  ]
  | unique_by(.tag_name | split("/")[0])
  | sort_by(.tag_name)
  | reverse
  | map({ tag_name, html_url, name })
  | if length == 0
      then error("no macOS arm64 image tags found")
      else .
    end
  '
)"

printf '%s\n' "$tags " | jq . > macos-image-tags.json
